import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { ProviderWrapper } from '../components/providers/provider-wrapper';
import { TabContainer } from '../components/ui/TabContainer';
import { classNames } from '../utils/classNames';
import './globals.css';

const montserrat = Montserrat({ weight: 'variable', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={classNames(
          montserrat,
          'dark h-full text-foreground bg-background'
        )}
      >
        <ProviderWrapper>
          <TabContainer />
          <main className="flex h-full flex-col items-center justify-between p-24">
            {children}
          </main>
        </ProviderWrapper>
      </body>
    </html>
  );
}
